/*
SQLyog Trial v12.15 (64 bit)
MySQL - 5.1.73 : Database - phone_dashboard_dev
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`phone_dashboard_dev` /*!40100 DEFAULT CHARACTER SET utf8 */;

USE `phone_dashboard_dev`;

/*Table structure for table `DMR_MOBILE_OUTFACT_DAILY` */

DROP TABLE IF EXISTS `DMR_MOBILE_OUTFACT_DAILY`;

CREATE TABLE `DMR_MOBILE_OUTFACT_DAILY` (
  `last_update` varchar(250) DEFAULT NULL,
  `cdt` varchar(250) DEFAULT NULL,
  `model` varchar(250) DEFAULT NULL,
  `storage` varchar(250) DEFAULT NULL,
  `zhishi` varchar(250) DEFAULT NULL,
  `color` varchar(250) DEFAULT NULL,
  `version` varchar(250) DEFAULT NULL,
  `out_day` varchar(250) DEFAULT NULL,
  `out_all` varchar(250) DEFAULT NULL,
  `dt` varchar(250) DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

/*Table structure for table `INTERFACE_BASE` */

DROP TABLE IF EXISTS `INTERFACE_BASE`;

CREATE TABLE `INTERFACE_BASE` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `INTERFACE_NAME` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=MyISAM AUTO_INCREMENT=45 DEFAULT CHARSET=utf8;

/*Table structure for table `INTERFACE_SUMMARY` */

DROP TABLE IF EXISTS `INTERFACE_SUMMARY`;

CREATE TABLE `INTERFACE_SUMMARY` (
  `INTERFACE_NAME` varchar(200) DEFAULT NULL COMMENT '接口名称',
  `REQUEST_TOTAL` int(11) DEFAULT NULL COMMENT '请求次数',
  `REQUEST_DATE` date DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

/*Table structure for table `PHONE_ACTIVATION_TIME` */

DROP TABLE IF EXISTS `PHONE_ACTIVATION_TIME`;

CREATE TABLE `PHONE_ACTIVATION_TIME` (
  `IMEI` varchar(100) DEFAULT NULL COMMENT '手机IMEI号',
  `LIVED_TIME` varchar(20) DEFAULT NULL COMMENT '开机时长',
  `CACTIVATION` varchar(20) DEFAULT NULL COMMENT '激活后联网半小时以上',
  `SOFTWARE_VERSION` varchar(32) DEFAULT NULL COMMENT '软件版本编',
  `EXTERNAL_MODEL` varchar(32) DEFAULT NULL COMMENT '外部机型',
  `GROUP_TITLE` varchar(32) DEFAULT NULL COMMENT '分组名称',
  `SUMMARY_DATE` varchar(20) DEFAULT NULL COMMENT '统计日期'
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='手机活跃时长统计表';

/*Table structure for table `PHONE_FAVORITES_SUMMARY` */

DROP TABLE IF EXISTS `PHONE_FAVORITES_SUMMARY`;

CREATE TABLE `PHONE_FAVORITES_SUMMARY` (
  `TOTAL_FAVORITE_FOR_PHONE` int(11) DEFAULT NULL COMMENT 'total_favorite_for_phone',
  `FAVORITE` int(11) DEFAULT NULL COMMENT '壁纸收藏次数',
  `SUMMARY_DATE` varchar(10) DEFAULT NULL COMMENT '统计日期',
  `IMEI` varchar(100) DEFAULT NULL COMMENT '手机IMEI号'
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='壁纸收藏统计表';

/*Table structure for table `PHONE_INTERFACE_BASE` */

DROP TABLE IF EXISTS `PHONE_INTERFACE_BASE`;

CREATE TABLE `PHONE_INTERFACE_BASE` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `INTERFACE_NAME` varchar(200) NOT NULL COMMENT '接口名称',
  PRIMARY KEY (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='接口基础表';

/*Table structure for table `PHONE_INTERFACE_SUMMARY` */

DROP TABLE IF EXISTS `PHONE_INTERFACE_SUMMARY`;

CREATE TABLE `PHONE_INTERFACE_SUMMARY` (
  `INTERFACE_NAME` varchar(200) NOT NULL COMMENT '接口名称',
  `REQUEST_DATE` datetime NOT NULL COMMENT '接口调用日期',
  `REQUEST_TOTAL` int(11) NOT NULL COMMENT '接口调用次数'
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='手机接口访问统计表';

/*Table structure for table `PHONE_PREVIEW_SUMMARY` */

DROP TABLE IF EXISTS `PHONE_PREVIEW_SUMMARY`;

CREATE TABLE `PHONE_PREVIEW_SUMMARY` (
  `TOTAL_PREVIEW` int(11) DEFAULT NULL COMMENT '壁纸预览总次数',
  `TOTAL_PREIVEW_FOR_PHONE` int(11) DEFAULT NULL COMMENT '壁纸预览手机数',
  `SUMMARY_DATE` varchar(10) DEFAULT NULL COMMENT '统计日期',
  `IMEI` varchar(100) DEFAULT NULL COMMENT '手机IMEI号'
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='手机壁纸预览次数统计';

/*Table structure for table `PHONE_RANDOM_CLOSE` */

DROP TABLE IF EXISTS `PHONE_RANDOM_CLOSE`;

CREATE TABLE `PHONE_RANDOM_CLOSE` (
  `RANDOM_DISABLE` int(11) DEFAULT NULL COMMENT '自动换壁纸关闭次数',
  `RANDOM_DISABLE_PHONE` int(11) DEFAULT NULL COMMENT '自动换壁纸关闭手机数',
  `SUMMARY_DATE` varchar(10) DEFAULT NULL COMMENT '统计日期',
  `IMEI` varchar(100) DEFAULT NULL COMMENT '手机IMEI号'
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='壁纸自动设置关闭统计表';

/*Table structure for table `PHONE_RANDOM_OPEN` */

DROP TABLE IF EXISTS `PHONE_RANDOM_OPEN`;

CREATE TABLE `PHONE_RANDOM_OPEN` (
  `RANDOM_ENABLE` int(11) DEFAULT NULL COMMENT '自动换壁纸开启次数',
  `RANDOM_FOR_PHONE` int(11) DEFAULT NULL COMMENT '自动换壁纸开启手机数',
  `SUMMARY_DATE` varchar(10) DEFAULT NULL COMMENT '统计日期',
  `IMEI` varchar(100) DEFAULT NULL COMMENT '手机IMEI号'
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='壁纸自动设置开启统计表';

/*Table structure for table `PHONE_SETTING_ALL` */

DROP TABLE IF EXISTS `PHONE_SETTING_ALL`;

CREATE TABLE `PHONE_SETTING_ALL` (
  `APPLY_ALL` int(11) DEFAULT NULL COMMENT '壁纸设置次数-同时',
  `PHONE_APPLY_ALL` int(11) DEFAULT NULL COMMENT '壁纸设置手机数-同时',
  `SUMMARY_DATE` varchar(10) DEFAULT NULL COMMENT '统计日期',
  `IMEI` varchar(100) DEFAULT NULL COMMENT '手机IMEI号'
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='壁纸设置同时';

/*Table structure for table `PHONE_SETTING_DESKTOP` */

DROP TABLE IF EXISTS `PHONE_SETTING_DESKTOP`;

CREATE TABLE `PHONE_SETTING_DESKTOP` (
  `APPLY_DESKTOP` int(11) DEFAULT NULL COMMENT '壁纸设置次数-桌面',
  `PHONE_APPLY_DESKTOP` int(11) DEFAULT NULL COMMENT '壁纸设置手机数-桌面',
  `SUMMARY_DATE` varchar(10) DEFAULT NULL COMMENT '统计日期',
  `IMEI` varchar(100) DEFAULT NULL COMMENT '手机IMEI号'
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='壁纸设置桌面';

/*Table structure for table `PHONE_SETTING_LOCK` */

DROP TABLE IF EXISTS `PHONE_SETTING_LOCK`;

CREATE TABLE `PHONE_SETTING_LOCK` (
  `APPLY_LOCK` int(11) DEFAULT NULL COMMENT '壁纸设置次数-锁屏',
  `PHONE_APPLY_LOCK` int(11) DEFAULT NULL COMMENT '壁纸设置手机数-锁屏',
  `SUMMARY_DATE` varchar(10) DEFAULT NULL COMMENT '统计日期',
  `IMEI` varchar(100) DEFAULT NULL COMMENT '手机IMEI号'
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='壁纸设置锁屏';

/*Table structure for table `PHONE_SETTING_SUMMARY` */

DROP TABLE IF EXISTS `PHONE_SETTING_SUMMARY`;

CREATE TABLE `PHONE_SETTING_SUMMARY` (
  `TOTAL_SETTING` int(11) DEFAULT NULL COMMENT '壁纸设置次数',
  `SETTING_FOR_PHONE` int(11) DEFAULT NULL COMMENT '壁纸设置手机数',
  `SUMMARY_DATE` varchar(10) DEFAULT NULL COMMENT '统计日期',
  `IMEI` varchar(100) DEFAULT NULL COMMENT '手机IMEI号'
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='壁纸设置统计表';

/*Table structure for table `PHONE_SHAKING_CLOSE` */

DROP TABLE IF EXISTS `PHONE_SHAKING_CLOSE`;

CREATE TABLE `PHONE_SHAKING_CLOSE` (
  `SHAKING_DISABLE` int(11) DEFAULT NULL COMMENT '摇一摇换壁纸关闭次数',
  `SHAKING_DISABLE_PHONE` int(11) DEFAULT NULL COMMENT '摇一摇换壁纸关闭手机数',
  `SUMMARY_DATE` varchar(10) DEFAULT NULL COMMENT '统计日期',
  `IMEI` varchar(100) DEFAULT NULL COMMENT '手机IMEI号'
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='摇一摇换壁纸关闭统计表';

/*Table structure for table `PHONE_SHAKING_OPEN` */

DROP TABLE IF EXISTS `PHONE_SHAKING_OPEN`;

CREATE TABLE `PHONE_SHAKING_OPEN` (
  `SHAKING_ENABLE` int(11) DEFAULT NULL COMMENT '摇一摇换壁纸开启次数',
  `SHAKING_ENABLE_PHONE` int(11) DEFAULT NULL COMMENT '摇一摇换壁纸开启手机数',
  `SUMMARY_DATE` varchar(10) DEFAULT NULL COMMENT '统计日期',
  `IMEI` varchar(100) DEFAULT NULL COMMENT '手机IMEI号'
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='摇一摇换壁纸统计表';

/*Table structure for table `PHONE_WALLPAPER_SUMMARY` */

DROP TABLE IF EXISTS `PHONE_WALLPAPER_SUMMARY`;

CREATE TABLE `PHONE_WALLPAPER_SUMMARY` (
  `TOTAL_PREVIEW` int(11) DEFAULT NULL COMMENT '壁纸预览总次数',
  `TOTAL_PREIVEW_FOR_PHONE` int(11) DEFAULT NULL COMMENT '壁纸预览手机数',
  `AVG_PREVIEW` int(11) DEFAULT NULL COMMENT '壁纸人均预览次数',
  `FAVORITE` int(11) DEFAULT NULL COMMENT '壁纸收藏次数',
  `TOTAL_FAVORITE_FOR_PHONE` int(11) DEFAULT NULL COMMENT 'total_favorite_for_phone',
  `TOTAL_SETTING` int(11) DEFAULT NULL COMMENT '壁纸设置次数',
  `SETTING_FOR_PHONE` int(11) DEFAULT NULL COMMENT '壁纸设置手机数',
  `APPLY_DESKTOP` int(11) DEFAULT NULL COMMENT '壁纸设置次数-桌面',
  `PHONE_APPLY_DESKTOP` int(11) DEFAULT NULL COMMENT '壁纸设置手机数-桌面',
  `APPLY_LOCK` int(11) DEFAULT NULL COMMENT '壁纸设置次数-锁屏',
  `PHONE_APPLY_LOCK` int(11) DEFAULT NULL COMMENT '壁纸设置手机数-锁屏',
  `APPLY_ALL` int(11) DEFAULT NULL COMMENT '壁纸设置次数-同时',
  `PHONE_APPLY_ALL` int(11) DEFAULT NULL COMMENT '壁纸设置手机数-同时',
  `RANDOM_ENABLE` int(11) DEFAULT NULL COMMENT '自动换壁纸开启次数',
  `RANDOM_FOR_PHONE` int(11) DEFAULT NULL COMMENT '自动换壁纸开启手机数',
  `RANDOM_DISABLE` int(11) DEFAULT NULL COMMENT '自动换壁纸关闭次数',
  `RANDOM_DISABLE_PHONE` int(11) DEFAULT NULL COMMENT '自动换壁纸关闭手机数',
  `SHAKING_ENABLE` int(11) DEFAULT NULL COMMENT '摇一摇换壁纸开启次数',
  `SHAKING_ENABLE_PHONE` int(11) DEFAULT NULL COMMENT '摇一摇换壁纸开启手机数',
  `SHAKING_DISABLE` int(11) DEFAULT NULL COMMENT '摇一摇换壁纸关闭次数',
  `SHAKING_DISABLE_PHONE` int(11) DEFAULT NULL COMMENT '摇一摇换壁纸关闭手机数',
  `SUMMARY_DATE` varchar(10) DEFAULT NULL COMMENT '统计日期'
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='手机壁纸统计表';

/*Table structure for table `PHONE_WALLPAPER_SUMMARY_IMEI` */

DROP TABLE IF EXISTS `PHONE_WALLPAPER_SUMMARY_IMEI`;

CREATE TABLE `PHONE_WALLPAPER_SUMMARY_IMEI` (
  `TOTAL_PREVIEW` int(11) DEFAULT NULL COMMENT '壁纸预览总次数',
  `TOTAL_PREIVEW_FOR_PHONE` int(11) DEFAULT NULL COMMENT '壁纸预览手机数',
  `AVG_PREVIEW` int(11) DEFAULT NULL COMMENT '壁纸人均预览次数',
  `FAVORITE` int(11) DEFAULT NULL COMMENT '壁纸收藏次数',
  `TOTAL_FAVORITE_FOR_PHONE` int(11) DEFAULT NULL COMMENT 'total_favorite_for_phone',
  `TOTAL_SETTING` int(11) DEFAULT NULL COMMENT '壁纸设置次数',
  `SETTING_FOR_PHONE` int(11) DEFAULT NULL COMMENT '壁纸设置手机数',
  `APPLY_DESKTOP` int(11) DEFAULT NULL COMMENT '壁纸设置次数-桌面',
  `PHONE_APPLY_DESKTOP` int(11) DEFAULT NULL COMMENT '壁纸设置手机数-桌面',
  `APPLY_LOCK` int(11) DEFAULT NULL COMMENT '壁纸设置次数-锁屏',
  `PHONE_APPLY_LOCK` int(11) DEFAULT NULL COMMENT '壁纸设置手机数-锁屏',
  `APPLY_ALL` int(11) DEFAULT NULL COMMENT '壁纸设置次数-同时',
  `PHONE_APPLY_ALL` int(11) DEFAULT NULL COMMENT '壁纸设置手机数-同时',
  `RANDOM_ENABLE` int(11) DEFAULT NULL COMMENT '自动换壁纸开启次数',
  `RANDOM_FOR_PHONE` int(11) DEFAULT NULL COMMENT '自动换壁纸开启手机数',
  `RANDOM_DISABLE` int(11) DEFAULT NULL COMMENT '自动换壁纸关闭次数',
  `RANDOM_DISABLE_PHONE` int(11) DEFAULT NULL COMMENT '自动换壁纸关闭手机数',
  `SHAKING_ENABLE` int(11) DEFAULT NULL COMMENT '摇一摇换壁纸开启次数',
  `SHAKING_ENABLE_PHONE` int(11) DEFAULT NULL COMMENT '摇一摇换壁纸开启手机数',
  `SHAKING_DISABLE` int(11) DEFAULT NULL COMMENT '摇一摇换壁纸关闭次数',
  `SHAKING_DISABLE_PHONE` int(11) DEFAULT NULL COMMENT '摇一摇换壁纸关闭手机数',
  `SUMMARY_DATE` varchar(10) DEFAULT NULL COMMENT '统计日期',
  `IMEI` varchar(100) DEFAULT NULL COMMENT '手机IMEI号'
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='手机壁纸统计表, 带IMEI分组';

/*Table structure for table `PHONE_WALLPAPER_SUMMARY_OBS` */

DROP TABLE IF EXISTS `PHONE_WALLPAPER_SUMMARY_OBS`;

CREATE TABLE `PHONE_WALLPAPER_SUMMARY_OBS` (
  `TOTAL_PREVIEW` int(11) DEFAULT NULL COMMENT '壁纸预览总次数',
  `TOTAL_PREIVEW_FOR_PHONE` int(11) DEFAULT NULL COMMENT '壁纸预览手机数',
  `AVG_PREVIEW` int(11) DEFAULT NULL COMMENT '壁纸人均预览次数',
  `FAVORITE` int(11) DEFAULT NULL COMMENT '壁纸收藏次数',
  `TOTAL_FAVORITE_FOR_PHONE` int(11) DEFAULT NULL COMMENT 'total_favorite_for_phone',
  `TOTAL_SETTING` int(11) DEFAULT NULL COMMENT '壁纸设置次数',
  `SETTING_FOR_PHONE` int(11) DEFAULT NULL COMMENT '壁纸设置手机数',
  `APPLY_DESKTOP` int(11) DEFAULT NULL COMMENT '壁纸设置次数-桌面',
  `PHONE_APPLY_DESKTOP` int(11) DEFAULT NULL COMMENT '壁纸设置手机数-桌面',
  `APPLY_LOCK` int(11) DEFAULT NULL COMMENT '壁纸设置次数-锁屏',
  `PHONE_APPLY_LOCK` int(11) DEFAULT NULL COMMENT '壁纸设置手机数-锁屏',
  `APPLY_ALL` int(11) DEFAULT NULL COMMENT '壁纸设置次数-同时',
  `PHONE_APPLY_ALL` int(11) DEFAULT NULL COMMENT '壁纸设置手机数-同时',
  `RANDOM_ENABLE` int(11) DEFAULT NULL COMMENT '自动换壁纸开启次数',
  `RANDOM_FOR_PHONE` int(11) DEFAULT NULL COMMENT '自动换壁纸开启手机数',
  `RANDOM_DISABLE` int(11) DEFAULT NULL COMMENT '自动换壁纸关闭次数',
  `RANDOM_DISABLE_PHONE` int(11) DEFAULT NULL COMMENT '自动换壁纸关闭手机数',
  `SHAKING_ENABLE` int(11) DEFAULT NULL COMMENT '摇一摇换壁纸开启次数',
  `SHAKING_ENABLE_PHONE` int(11) DEFAULT NULL COMMENT '摇一摇换壁纸开启手机数',
  `SHAKING_DISABLE` int(11) DEFAULT NULL COMMENT '摇一摇换壁纸关闭次数',
  `SHAKING_DISABLE_PHONE` int(11) DEFAULT NULL COMMENT '摇一摇换壁纸关闭手机数',
  `SUMMARY_DATE` varchar(10) DEFAULT NULL COMMENT '统计日期',
  `IMEI` varchar(100) DEFAULT NULL COMMENT '手机IMEI号',
  `SOFTWARE_VERSION` varchar(32) DEFAULT NULL COMMENT '软件版本编',
  `EXTERNAL_MODEL` varchar(32) DEFAULT NULL COMMENT '外部机型',
  `GROUP_TITLE` varchar(32) DEFAULT NULL COMMENT '分组名称'
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='手机壁纸统计表, 增加观测维度';

/*Table structure for table `SUM_BY_DAY` */

DROP TABLE IF EXISTS `SUM_BY_DAY`;

CREATE TABLE `SUM_BY_DAY` (
  `SUMMARY_DATE` varchar(10) DEFAULT NULL,
  `TOTAL_BY` int(11) DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

/*Table structure for table `TV_DEVICE_COUNT` */

DROP TABLE IF EXISTS `TV_DEVICE_COUNT`;

CREATE TABLE `TV_DEVICE_COUNT` (
  `MODEL` varchar(32) DEFAULT NULL,
  `C_DEVICE` varchar(32) DEFAULT NULL,
  `C_BOOTSTRAP` varchar(32) DEFAULT NULL,
  `C_HEARTBEAT` varchar(32) DEFAULT NULL,
  `SUMMARY_DATE` varchar(10) DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

/*Table structure for table `TV_NETWORK_HALFHOUR` */

DROP TABLE IF EXISTS `TV_NETWORK_HALFHOUR`;

CREATE TABLE `TV_NETWORK_HALFHOUR` (
  `active_count` varchar(250) DEFAULT NULL COMMENT '激活数',
  `software_version` varchar(250) DEFAULT NULL COMMENT '手机版本',
  `external_model` varchar(250) DEFAULT NULL COMMENT '外部型号',
  `group_title` varchar(250) DEFAULT NULL COMMENT '分组名称',
  `summary_date` varchar(250) DEFAULT NULL COMMENT '日期'
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='开机半小时统计表';

/*Table structure for table `test_20151029` */

DROP TABLE IF EXISTS `test_20151029`;

CREATE TABLE `test_20151029` (
  `TOTAL_PREVIEW` int(11) DEFAULT NULL COMMENT '壁纸预览总次数',
  `TOTAL_PREIVEW_FOR_PHONE` int(11) DEFAULT NULL COMMENT '壁纸预览手机数',
  `AVG_PREVIEW` int(11) DEFAULT NULL COMMENT '壁纸人均预览次数',
  `FAVORITE` int(11) DEFAULT NULL COMMENT '壁纸收藏次数',
  `TOTAL_FAVORITE_FOR_PHONE` int(11) DEFAULT NULL COMMENT 'total_favorite_for_phone',
  `TOTAL_SETTING` int(11) DEFAULT NULL COMMENT '壁纸设置次数',
  `SETTING_FOR_PHONE` int(11) DEFAULT NULL COMMENT '壁纸设置手机数',
  `APPLY_DESKTOP` int(11) DEFAULT NULL COMMENT '壁纸设置次数-桌面',
  `PHONE_APPLY_DESKTOP` int(11) DEFAULT NULL COMMENT '壁纸设置手机数-桌面',
  `APPLY_LOCK` int(11) DEFAULT NULL COMMENT '壁纸设置次数-锁屏',
  `PHONE_APPLY_LOCK` int(11) DEFAULT NULL COMMENT '壁纸设置手机数-锁屏',
  `APPLY_ALL` int(11) DEFAULT NULL COMMENT '壁纸设置次数-同时',
  `PHONE_APPLY_ALL` int(11) DEFAULT NULL COMMENT '壁纸设置手机数-同时',
  `RANDOM_ENABLE` int(11) DEFAULT NULL COMMENT '自动换壁纸开启次数',
  `RANDOM_FOR_PHONE` int(11) DEFAULT NULL COMMENT '自动换壁纸开启手机数',
  `RANDOM_DISABLE` int(11) DEFAULT NULL COMMENT '自动换壁纸关闭次数',
  `RANDOM_DISABLE_PHONE` int(11) DEFAULT NULL COMMENT '自动换壁纸关闭手机数',
  `SHAKING_ENABLE` int(11) DEFAULT NULL COMMENT '摇一摇换壁纸开启次数',
  `SHAKING_ENABLE_PHONE` int(11) DEFAULT NULL COMMENT '摇一摇换壁纸开启手机数',
  `SHAKING_DISABLE` int(11) DEFAULT NULL COMMENT '摇一摇换壁纸关闭次数',
  `SHAKING_DISABLE_PHONE` int(11) DEFAULT NULL COMMENT '摇一摇换壁纸关闭手机数',
  `SUMMARY_DATE` varchar(10) DEFAULT NULL COMMENT '统计日期'
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='手机壁纸统计表';

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
