#!/bin/bash

hive -e "SHOW CREATE TABLE tv_report.appinstall                     "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.appuninstall                   "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.avro_appstartup                "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.avro_bootstrap                 "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.avro_bootstrap_tmp             "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.avro_endplay                   "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.avro_heartbeat                 "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.avro_startplay                 "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.boot_oversea                   "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.browser_dur                    "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.browser_ver                    "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.browserbaidusrch               "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.browserbaiduvideosrch          "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.browserheartbeat               "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.browserlink                    "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.browsernav                     "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.browsernew                     "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.browserplayvideo               "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.browserstartup                 "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.cdndispatch                    "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.devicetrace                    "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.errlog                         "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.geraction                      "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.gerdur                         "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.gerheartbeat                   "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.gernew                         "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.gerstartup                     "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.ggtemp                         "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.hk_activate_count              "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.hk_activate_delta              "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.hk_app_startup_daily           "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.hk_bootstrap_all               "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.hk_bootstrap_daily             "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.hk_carousel_play_daily         "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.hk_carousel_plist_show_daily   "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.hk_carousel_time_daily         "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.hk_desktop_show_daily          "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.hk_desktop_startup             "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.hk_online_time_daily           "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.hk_osver_daily                 "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.hk_prmdposter_click_daily      "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.hk_program_choose_daily        "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.hk_program_show_daily          "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.hk_search_count_daily          "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.hk_shposter_click_count        "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.hk_upgrade_count               "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.hk_user_register_daily         "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.iptv_box                       "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.iptv_group                     "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.iptv_mode                      "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.iptv_upgrade                   "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.letv_play_dur                  "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.letvblock                      "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.letvchswitch                   "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.letvend                        "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.letvenv                        "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.letvinit                       "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.letvplay                       "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.letvplistshow                  "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.letvtime                       "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.mobileappboot                  "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.mobileappinstall               "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.ott_box                        "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.oversea_tv_ad                  "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.oversea_tv_ad_20150422         "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.oversea_tv_ad_20151112         "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.oversea_tv_env                 "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.oversea_tv_env_20150422        "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.oversea_tv_env_20151112        "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.oversea_tv_er                  "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.oversea_tv_er_20150422         "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.oversea_tv_er_20151112         "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.oversea_tv_hkanyplex           "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.oversea_tv_login               "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.oversea_tv_login_20150422      "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.oversea_tv_login_20151112      "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.oversea_tv_new                 "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.oversea_tv_op                  "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.oversea_tv_op_20150422         "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.oversea_tv_op_20151112         "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.oversea_tv_play                "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.oversea_tv_play_20150422       "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.oversea_tv_play_20151112       "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.oversea_tv_pv                  "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.oversea_tv_pv_20150422         "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.oversea_tv_pv_20151112         "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.oversea_tv_qy                  "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.oversea_tv_qy_20150422         "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.oversea_tv_qy_20151112         "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.overseas_tv_activate_count     "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.overseas_tv_activate_delta     "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.overseas_tv_bootstrap_all      "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.overseas_tv_bootstrap_daily    "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.overseas_tv_login_all          "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.overseas_tv_login_daily        "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.overseas_tv_play_daily         "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.playblock                      "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.playend                        "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.playerror                      "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.playinit                       "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.playseek                       "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.playstart                      "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.playtime                       "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.resource_app                   "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.resource_channellist           "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.resource_country               "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.resource_province              "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.sdkappcrash                    "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.sdkappdur                      "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.sdkapperror                    "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.sdkapppagejump                 "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.sdkappstartup                  "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.sdkcustomevent                 "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.shutdown                       "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.stag_appstartup_mac_pn         "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.stat_crash_daily               "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.stat_crash_total               "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.stat_dur_daily                 "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.stat_dur_total                 "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.stat_error_detail              "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.stat_error_total               "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.stat_new_daily                 "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.stat_new_total                 "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.stat_open_daily                "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.stat_open_monthly              "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.stat_open_total                "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.stat_open_weekly               "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.stat_pagejump_daily            "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.stat_pageview_daily            "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.stat_pageview_total            "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.stat_url_daily                 "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.surf                           "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.temp                           "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.tvaction                       "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.tvplusend                      "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.tvplusinit                     "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.tvplusplay                     "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.tvplustime                     "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.tvremoterbtn                   "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.unicom_mac                     "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.updownloadfinish               "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.updownloadstartup              "  >>  /home/kanghua/tv_report_ddl.sql
hive -e "SHOW CREATE TABLE tv_report.upfinish                       "  >>  /home/kanghua/tv_report_ddl.sql