DROP TABLE IF EXISTS `PHONE_ACTIVATION_TIME_BK`;

CREATE TABLE `PHONE_ACTIVATION_TIME_BK` AS
SELECT
  `CIMEI`,
  `SLIVED_TIME`,
  `SOFTWARE_VERSION`,
  `EXTERNAL_MODEL`,
  `GROUP_TITLE`,
  `SUMMARY_DATE`
FROM
  `phone_dashboard`.`PHONE_ACTIVATION_TIME`
WHERE `SUMMARY_DATE` IN (
    '20160122',
    '20160123',
    '20160124'
  )
GROUP BY `CIMEI`,
  `SLIVED_TIME`,
  `SOFTWARE_VERSION`,
  `EXTERNAL_MODEL`,
  `GROUP_TITLE`,
  `SUMMARY_DATE`   ;
  
-- Delete   
DELETE
FROM
  `phone_dashboard`.`PHONE_ACTIVATION_TIME`
WHERE `SUMMARY_DATE` IN (
    '20160122',
    '20160123',
    '20160124'
  )
  
-- Insert
INSERT INTO `phone_dashboard`.`PHONE_ACTIVATION_TIME`
SELECT
  *
FROM
  `PHONE_ACTIVATION_TIME_BK`
WHERE `SUMMARY_DATE` IN (
    '20160122',
    '20160123',
    '20160124'
  )
  